spring.application.name=NotificationService
# Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from=noreply@task-tracker.com
# Debug
logging.level.org.springframework.web=DEBUG
logging.level.org.example.task_tracker=DEBUG
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=latest
# Actuator
server.port=8081
management.endpoints.web.exposure.include=health,metrics